runtime: python39
entrypoint: python main.py

handlers:
  - url: /.*
    script: auto
    # - url: /
    #   script: src/main.py
    # - url: /scenario
    #   script: src/main.py
    # - url: /finished
    #   script: src/main.py
# # This handler routes all requests not caught above to your main app. It is
# # required when static routes are defined, but can be omitted (along with
# # the entire handlers section) when there are no static files defined.
# - url: /.*
#   script: auto
